# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d22841898c48a7613723c725f63be907eeac01648438b1962ff89b5f89bb67693aa9c8bc23df92f3cb786b2e0fe5a38bef2867d652b9371e2ba68fc581b68bd2

test:
  secret_key_base: 9db88c4b9729c83d5aa4f73d0675bee0463e56aa7cec70d2a366a364b76e6298b1089fc6d7cddd264dc9f6fcebb8cb05337d214fd8c988f590937af1b59b79bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
